import { splitToEqualPartsArray } from "./../function/MathFunctions.js";

export const GAME_SCREEN = "GameScreen";

/** Menu. */
export const ASSET_BUTTON_COMPONENT_PERCENT_X = 3;
export const ASSET_BUTTON_COMPONENT_PERCENT_Y = 3;
export const ASSET_BUTTON_COMPONENT_PERCENT_R = 24;
export const ASSET_BUTTON_COMPONENT_COLOR = "yellow";
export const ASSET_BUTTON_COMPONENT_PERCENT_BORDER = .2;
export const ASSET_BUTTON_COMPONENT_BORDER_COLOR = "white";

export const GAME_SCREEN_H_BORDER_PERCENT = 3;
export const GAME_SCREEN_TOP_BORDER_PERCENT = 3;
export const GAME_SCREEN_BOTTOM_BORDER_PERCENT = 3;

/** Default Grid Settings. */
export const GAME_SCREEN_GRID_TITLE_TYPE = "14pt Helvetica";
export const GAME_SCREEN_GRID_TITLE_COLOR = "white";
export const GAME_SCREEN_GRID_TITLE_PERCENT_OFFSET_X = .3;
export const GAME_SCREEN_GRID_TITLE_PERCENT_OFFSET_Y = 2.5;
export const GAME_SCREEN_GRID_TEXT_TYPE = "12pt Helvetica";
export const GAME_SCREEN_GRID_TEXT_COLOR = "white";
export const GAME_SCREEN_GRID_TEXT_PERCENT_OFFSET_X = .3;
export const GAME_SCREEN_GRID_TEXT_PERCENT_OFFSET_Y = 2.5;

/** Profile Picture. */
export const GAME_SCREEN_PROFILE_PICTURE_PERCENT_X = 3;
export const GAME_SCREEN_PROFILE_PICTURE_PERCENT_Y = 3;
export const GAME_SCREEN_PROFILE_PICTURE_PERCENT_WH = 24;
export const GAME_SCREEN_PROFILE_PICTURE_PERCENT_BORDER = .2;
export const GAME_SCREEN_PROFILE_PICTURE_COLOR = "white";
export const IMAGE_FACE_RASPBERRY_SRC = "./images/opensource/gpl/papirus-icon-theme/48x48/emotes/face-raspberry.svg";
export const IMAGE_FACE_RASPBERRY_WH = 48;
export const IMAGE_FACE_RASPBERRY_PERCENT_X = 3;
export const IMAGE_FACE_RASPBERRY_PERCENT_Y = 3;
export const IMAGE_FACE_RASPBERRY_PERCENT_WH = 24;

/** Job Title & Salary */
export const GAME_SCREEN_JOB_TITLE_TEXT_PERCENT_X = 14;
export const GAME_SCREEN_JOB_TITLE_TEXT_PERCENT_Y = 7;
export const GAME_SCREEN_JOB_TITLE_TEXT_TYPE = "32pt Helvetica";
export const GAME_SCREEN_JOB_TITLE_TEXT_COLOR = "white";
export const GAME_SCREEN_JOB_TITLE_SALARY_TEXT_PERCENT_X = 14;
export const GAME_SCREEN_JOB_TITLE_SALARY_TEXT_PERCENT_Y = 13;
export const GAME_SCREEN_JOB_TITLE_SALARY_TEXT_TYPE = "32pt Helvetica";
export const GAME_SCREEN_JOB_TITLE_SALARY_TEXT_COLOR = "green";

/** Next Year Button */
export const GAME_SCREEN_NEXT_YEAR_BUTTON_DEFAULT_BACKGROUND_COLOR = "black";
export const GAME_SCREEN_NEXT_YEAR_BUTTON_ON_MOUSE_OVER_BACKGROUND_COLOR = "cyan";
export const GAME_SCREEN_NEXT_YEAR_BUTTON_ON_CLICK_BACKGROUND_COLOR = "green";
export const GAME_SCREEN_NEXT_YEAR_BUTTON_PERCENT_X = 80;
export const GAME_SCREEN_NEXT_YEAR_BUTTON_PERCENT_Y = 3;
export const GAME_SCREEN_NEXT_YEAR_BUTTON_PERCENT_W = 17;
export const GAME_SCREEN_NEXT_YEAR_BUTTON_PERCENT_H = 8;
export const GAME_SCREEN_NEXT_YEAR_BUTTON_PERCENT_BORDER = .2;
export const GAME_SCREEN_NEXT_YEAR_BUTTON_COLOR = "white";
export const GAME_SCREEN_NEXT_YEAR_BUTTON_TEXT = "NEXT YEAR";
export const GAME_SCREEN_NEXT_YEAR_BUTTON_TEXT_PERCENT_X = 81;
export const GAME_SCREEN_NEXT_YEAR_BUTTON_TEXT_PERCENT_Y = 8.8;
export const GAME_SCREEN_NEXT_YEAR_BUTTON_TEXT_FONT = "29pt Helvetica";
export const GAME_SCREEN_NEXT_YEAR_BUTTON_TEXT_COLOR = "white";
export const IMAGE_PLAY_SRC = "./images/opensource/gpl/papirus_icons/src/apps_ac3_player.svg";
export const IMAGE_PLAY_WH = 192;
export const IMAGE_PLAY_PERCENT_X = 93;
export const IMAGE_PLAY_PERCENT_Y = 3;
export const IMAGE_PLAY_PERCENT_WH = 8;

/** Asset Table Component. */
export const GAME_SCREEN_ASSET_PERCENT_X = 2;
export const GAME_SCREEN_ASSET_PERCENT_Y = 60;
export const GAME_SCREEN_ASSET_PERCENT_W_ARRAY = [9, 5, 3, 3, 1.5, 2.2, 2.5, 1.5, 2.2, 2.5];
export const GAME_SCREEN_ASSET_PERCENT_H_ARRAY = splitToEqualPartsArray(36, 12);
export const GAME_SCREEN_ASSET_PERCENT_BORDER = .2;
export const GAME_SCREEN_ASSET_COLOR = "green";

/** Salary Component. */
export const GAME_SCREEN_SALARY_TITLE_TEXT_PERCENT_X = 3;
export const GAME_SCREEN_SALARY_TITLE_TEXT_PERCENT_Y = 32;
export const GAME_SCREEN_SALARY_TITLE_TEXT_TYPE = "29pt Helvetica";
export const GAME_SCREEN_SALARY_TITLE_TEXT_COLOR = "white";
export const GAME_SCREEN_SALARY_TEXT_PERCENT_X = 10;
export const GAME_SCREEN_SALARY_TEXT_PERCENT_Y = 32;
export const GAME_SCREEN_SALARY_TEXT_TYPE = "29pt Helvetica";
export const GAME_SCREEN_SALARY_TEXT_COLOR = "green";
export const GAME_SCREEN_BONUS_TITLE_TEXT_PERCENT_X = 3;
export const GAME_SCREEN_BONUS_TITLE_TEXT_PERCENT_Y = 38;
export const GAME_SCREEN_BONUS_TITLE_TEXT_TYPE = "29pt Helvetica";
export const GAME_SCREEN_BONUS_TITLE_TEXT_COLOR = "white";
export const GAME_SCREEN_BONUS_TEXT_PERCENT_X = 10;
export const GAME_SCREEN_BONUS_TEXT_PERCENT_Y = 38;
export const GAME_SCREEN_BONUS_TEXT_TYPE = "29pt Helvetica";
export const GAME_SCREEN_BONUS_TEXT_COLOR = "green";
export const GAME_SCREEN_STOCK_OPTIONS_TITLE_TEXT_PERCENT_X = 3;
export const GAME_SCREEN_STOCK_OPTIONS_TITLE_TEXT_PERCENT_Y = 44;
export const GAME_SCREEN_STOCK_OPTIONS_TITLE_TEXT_TYPE = "29pt Helvetica";
export const GAME_SCREEN_STOCK_OPTIONS_TITLE_TEXT_COLOR = "white";
export const GAME_SCREEN_STOCK_OPTIONS_TEXT_PERCENT_X = 17;
export const GAME_SCREEN_STOCK_OPTIONS_TEXT_PERCENT_Y = 44;
export const GAME_SCREEN_STOCK_OPTIONS_TEXT_TYPE = "29pt Helvetica";
export const GAME_SCREEN_STOCK_OPTIONS_TEXT_COLOR = "green";

/** Asset Images Component. */
export const GAME_SCREEN_ASSET_IMAGE_PERCENT_X = 35;
export const GAME_SCREEN_ASSET_IMAGE_PERCENT_Y = 60;
export const GAME_SCREEN_ASSET_IMAGE_PERCENT_W = 27.5;
export const GAME_SCREEN_ASSET_IMAGE_PERCENT_H = 36;
export const GAME_SCREEN_ASSET_IMAGE_PERCENT_BORDER = .2;
export const GAME_SCREEN_ASSET_IMAGE_COLOR = "white";

export const GAME_SCREEN_LIABILITY_PERCENT_X = 63;
export const GAME_SCREEN_LIABILITY_PERCENT_Y = 60;
export const GAME_SCREEN_LIABILITY_PERCENT_W_ARRAY = [9, 5, 1.5, 2.2, 2.5];
export const GAME_SCREEN_LIABILITY_PERCENT_H_ARRAY = splitToEqualPartsArray(36, 12);
export const GAME_SCREEN_LIABILITY_PERCENT_BORDER = .2;
export const GAME_SCREEN_LIABILITY_COLOR = "red";

export const GAME_SCREEN_REVENUE_PERCENT_X = 2;
export const GAME_SCREEN_REVENUE_PERCENT_Y = 60;
export const GAME_SCREEN_REVENUE_PERCENT_W_ARRAY = [9, 5];
export const GAME_SCREEN_REVENUE_PERCENT_H_ARRAY = splitToEqualPartsArray(36, 12);
export const GAME_SCREEN_REVENUE_PERCENT_BORDER = .2;
export const GAME_SCREEN_REVENUE_COLOR = "green";

export const GAME_SCREEN_EXPENSE_PERCENT_X = 84.2;
export const GAME_SCREEN_EXPENSE_PERCENT_Y = 60;
export const GAME_SCREEN_EXPENSE_PERCENT_W_ARRAY = [9, 5];
export const GAME_SCREEN_EXPENSE_PERCENT_H_ARRAY = splitToEqualPartsArray(36, 12);
export const GAME_SCREEN_EXPENSE_PERCENT_BORDER = .2;
export const GAME_SCREEN_EXPENSE_COLOR = "red";

export const GAME_SCREEN_FINANCIALS_PERCENT_X = 2;
export const GAME_SCREEN_FINANCIALS_PERCENT_Y = 2;
export const GAME_SCREEN_FINANCIALS_PERCENT_W = 96;
export const GAME_SCREEN_FINANCIALS_PERCENT_H = 56;
export const GAME_SCREEN_FINANCIALS_PERCENT_BORDER = .2;
export const GAME_SCREEN_FINANCIALS_COLOR = "white";



export const GAME_SCREEN_LAST_YEAR_REVENUE_PERCENT_X = 38;
export const GAME_SCREEN_LAST_YEAR_REVENUE_PERCENT_Y = 16;
export const GAME_SCREEN_LAST_YEAR_REVENUE_PERCENT_W_ARRAY = [11, 7];
export const GAME_SCREEN_LAST_YEAR_REVENUE_PERCENT_H_ARRAY = splitToEqualPartsArray(36, 12);
export const GAME_SCREEN_LAST_YEAR_REVENUE_PERCENT_BORDER = .2;
export const GAME_SCREEN_LAST_YEAR_REVENUE_COLOR = "green";

export const GAME_SCREEN_LAST_YEAR_EXPENSE_PERCENT_X = 63;
export const GAME_SCREEN_LAST_YEAR_EXPENSE_PERCENT_Y = 16;
export const GAME_SCREEN_LAST_YEAR_EXPENSE_PERCENT_W_ARRAY = [11, 7];
export const GAME_SCREEN_LAST_YEAR_EXPENSE_PERCENT_H_ARRAY = splitToEqualPartsArray(36, 12);
export const GAME_SCREEN_LAST_YEAR_EXPENSE_PERCENT_BORDER = .2;
export const GAME_SCREEN_LAST_YEAR_EXPENSE_COLOR = "red";

export const GAME_SCREEN_LAST_YEAR_GRID_TITLE_TYPE = "18pt Helvetica";
export const GAME_SCREEN_LAST_YEAR_GRID_TITLE_COLOR = "white";
export const GAME_SCREEN_LAST_YEAR_GRID_TITLE_PERCENT_OFFSET_X = .3;
export const GAME_SCREEN_LAST_YEAR_GRID_TITLE_PERCENT_OFFSET_Y = 2.5;

export const GAME_SCREEN_LAST_YEAR_GRID_TEXT_TYPE = "16pt Helvetica";
export const GAME_SCREEN_LAST_YEAR_GRID_TEXT_COLOR = "white";
export const GAME_SCREEN_LAST_YEAR_GRID_TEXT_PERCENT_OFFSET_X = .3;
export const GAME_SCREEN_LAST_YEAR_GRID_TEXT_PERCENT_OFFSET_Y = 2.5;

export const GAME_SCREEN_LAST_YEAR_NET_INCOME_TEXT_PERCENT_X = 52;
export const GAME_SCREEN_LAST_YEAR_NET_INCOME_TEXT_PERCENT_Y = 82;
export const GAME_SCREEN_LAST_YEAR_NET_INCOME_TEXT_TYPE = "50pt Helvetica";
export const GAME_SCREEN_LAST_YEAR_NET_INCOME_TEXT_POSITIVE_COLOR = "green";
export const GAME_SCREEN_LAST_YEAR_NET_INCOME_TEXT_NEGATIVE_COLOR = "red";



